#!/bin/bash

rm -rf build/h5
mkdir build/h5

cd build

echo -e "\nTesting simple data read/write...\n"
./SimpleDataTest.cpp.out

echo -e "\nTesting reading/writing attributes...\n"
./AttributesTest.cpp.out

echo -e "\nTesting append data...\n"
./AppendTest.cpp.out

echo -e "\nTesting file accesses...\n"
./FileAccessTest.cpp.out

echo -e "\nTesting striding access...\n"
./StridingTest.cpp.out

echo -e "\nTesting removing datasets...\n"
./RemoveTest.cpp.out

echo -e "\nTesting references...\n"
./ReferencesTest.cpp.out


echo -e "\nTesting simple data read/write (parallel)...\n"
mpirun -n 8 ./Parallel_SimpleDataTest.cpp.out

echo -e "\nTesting reading/writing attributes (parallel)...\n"
mpirun -n 4 ./Parallel_AttributesTest.cpp.out

echo -e "\nTesting removing datasets (parallel)...\n"
mpirun -n 2 ./Parallel_RemoveTest.cpp.out

echo -e "\nTesting references (parallel)...\n"
mpirun -n 2 ./Parallel_ReferencesTest.cpp.out


cd ..

