#!/bin/bash

dir=${1:-build}

rm -rf $dir/h5
mkdir $dir/h5

cd $dir
OK=0

function testIt()
{
    if [ -e "$1" ]; then
        echo -e "\n$2\n"
        eval $1
        OK=$(( OK + $? ))
    fi
}

testIt ./SimpleDataTest.cpp.out "Testing simple data read/write..."

testIt ./AttributesTest.cpp.out "Testing reading/writing attributes..."

testIt ./AppendTest.cpp.out "Testing append data..."

testIt ./FileAccessTest.cpp.out "Testing file accesses..."

testIt ./StridingTest.cpp.out "Testing striding access..."

testIt ./RemoveTest.cpp.out "Testing removing datasets..."

testIt ./ReferencesTest.cpp.out "Testing references..."

testIt "mpirun -n 8 ./DomainsTest.cpp.out" "Testing domains..."

#testIt "mpirun -n 1 ./MergedReadTest.cpp.out" "Testing merged read..."

cd ..

exit $OK
