#!/bin/bash

rm -rf build/h5
mkdir build/h5

cd build
OK=0

echo -e "\nTesting simple data read/write...\n"
./SimpleDataTest.cpp.out
OK=$(( OK + $? ))

echo -e "\nTesting reading/writing attributes...\n"
./AttributesTest.cpp.out
OK=$(( OK + $? ))

echo -e "\nTesting append data...\n"
./AppendTest.cpp.out
OK=$(( OK + $? ))

echo -e "\nTesting file accesses...\n"
./FileAccessTest.cpp.out
OK=$(( OK + $? ))

echo -e "\nTesting striding access...\n"
./StridingTest.cpp.out
OK=$(( OK + $? ))

echo -e "\nTesting removing datasets...\n"
./RemoveTest.cpp.out
OK=$(( OK + $? ))

echo -e "\nTesting references...\n"
./ReferencesTest.cpp.out
OK=$(( OK + $? ))

echo -e "\nTesting domains...\n"
mpirun -n 8 ./DomainsTest.cpp.out
OK=$(( OK + $? ))

#echo -e "\nTesting merged read...\n"
#mpirun -n 1 ./MergedReadTest.cpp.out

cd ..

exit $OK
