#!/bin/bash

dir=${1:-build}

rm -rf $dir/h5
mkdir $dir/h5

cd $dir
OK=0

function testIt()
{
    if [ -e "$1" ]; then
        echo -e "\n$2\n"
        eval $1
        OK=$(( OK + $? ))
    fi
}

testIt ./SimpleDataTest.cpp.out "Testing simple data read/write..."

testIt ./AttributesTest.cpp.out "Testing reading/writing attributes..."

testIt ./AppendTest.cpp.out "Testing append data..."

testIt ./FileAccessTest.cpp.out "Testing file accesses..."

testIt ./StridingTest.cpp.out  "Testing striding access..."

testIt ./RemoveTest.cpp.out "Testing removing datasets..."

testIt ./ReferencesTest.cpp.out "Testing references..."

#testIt "mpirun -n 8 ./Parallel_SimpleDataTest.cpp.out" "Testing simple data read/write (parallel)..."

testIt "mpirun -n 8 ./Parallel_DomainsTest.cpp.out" "Testing domains (parallel)..."

testIt "mpirun -n 4 ./Parallel_AttributesTest.cpp.out" "Testing reading/writing attributes (parallel)..."

testIt "mpirun -n 2 ./Parallel_RemoveTest.cpp.out" "Testing removing datasets (parallel)..."

testIt "mpirun -n 2 ./Parallel_ReferencesTest.cpp.out" "Testing references (parallel)..."

cd ..

exit $OK
