#!/usr/bin/env bash
#
# Copyright 2013-2015 Felix Schmitt, Axel Huebl
#
# This file is part of libSplash.
#
# libSplash is free software: you can redistribute it and/or modify
# it under the terms of of either the GNU General Public License or
# the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# libSplash is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License and the GNU Lesser General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# and the GNU Lesser General Public License along with libSplash.
# If not, see <http://www.gnu.org/licenses/>.
#

if [ $# -eq 0 ]; then
    echo "  WARNING:"
    echo "    No path for build director was given."
    echo "    Will use \"build\" instead."
fi

dir=${1:-build}

rm -rf $dir/h5
mkdir $dir/h5

cd $dir
OK=0

function testLast()
{
    if [ $1 -ne 0 ]; then
        echo "An error occured in $2..."
    fi
}
function testSerial()
{
    if [ -e "$1" ]; then
        echo -e "\n$2\n"
        $1
        last=$?
        testLast $last $1
        OK=$(( OK + $last ))
    fi
}
function testMPI()
{
    if [ -e "$1" ]; then
        echo -e "\n$3\n"
        mpirun -n $2 $1
        last=$?
        testLast $last $1
        OK=$(( OK + $last ))
    fi
}

testSerial ./SimpleDataTest.cpp.out "Testing simple data read/write..."

testSerial ./AttributesTest.cpp.out "Testing reading/writing attributes..."
testSerial ./readBoolChar.py "Testing h5py compatible read..."

testSerial ./AppendTest.cpp.out "Testing append data..."

testSerial ./FileAccessTest.cpp.out "Testing file accesses..."

testSerial ./StridingTest.cpp.out "Testing striding access..."

testSerial ./RemoveTest.cpp.out "Testing removing datasets..."

testSerial ./ReferencesTest.cpp.out "Testing references..."

testMPI ./DomainsTest.cpp.out 8 "Testing domains..."

cd ..

exit $OK
