#!/usr/bin/env bash
#
# Copyright 2013-2015 Felix Schmitt, Axel Huebl
#
# This file is part of libSplash.
#
# libSplash is free software: you can redistribute it and/or modify
# it under the terms of of either the GNU General Public License or
# the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# libSplash is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License and the GNU Lesser General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# and the GNU Lesser General Public License along with libSplash.
# If not, see <http://www.gnu.org/licenses/>.
#

if [ $# -eq 0 ]; then
    echo "  WARNING:"
    echo "    No path for build director was given."
    echo "    Will use \"build\" instead."
fi

dir=${1:-build}

rm -rf $dir/h5
mkdir $dir/h5

cd $dir
OK=0

function testLast()
{
    if [ $1 -ne 0 ]; then
        echo "An error occured in $2..."
    fi
}
function testMPI()
{
    if [ $( whoami ) == "root" ]; then
       APPEND_OK_ROOT_DOCKER="--allow-run-as-root"
    fi
    if [ -e "$1" ]; then
        echo -e "\n$3\n"
        mpirun $APPEND_OK_ROOT_DOCKER -n $2 $1
        last=$?
        testLast $last $1
        OK=$(( OK + $last ))
    fi
}

testMPI ./Parallel_SimpleDataTest.cpp.out 8 "Testing simple data read/write (parallel)..."
testMPI ./Parallel_FilenameTest.cpp.out 1 "Testing file naming (parallel)..."

testMPI ./Parallel_SerialDC.cpp.out 8 "Testing SerialDataCollector (parallel)..."

testMPI ./Parallel_ListFilesTest.cpp.out 1 "Testing list files (parallel)..."

testMPI ./Parallel_DomainsTest.cpp.out 8 "Testing domains (parallel)..."

testMPI ./Parallel_AttributesTest.cpp.out 4 "Testing reading/writing attributes (parallel)..."

testMPI ./Parallel_RemoveTest.cpp.out 2 "Testing removing datasets (parallel)..."

testMPI ./Parallel_ReferencesTest.cpp.out 2 "Testing references (parallel)..."

testMPI ./Parallel_ZeroAccessTest.cpp.out 2 "Testing zero accesses 2 (parallel)..."

testMPI ./Parallel_ZeroAccessTest.cpp.out 4 "Testing zero accesses 4 (parallel)..."

testMPI ./Parallel_ZeroAccessTest.cpp.out 7 "Testing zero accesses 7 (parallel)..."

cd ..

exit $OK
